// <auto-generated />
using System;
using BlazorAV.Infrastructure.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAV.Infrastructure.Migrations
{
    [DbContext(typeof(BlazorAVContext))]
    [Migration("20220527180230_Initail")]
    partial class Initail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorAV.Core.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PortalAccess")
                        .HasColumnType("bit");

                    b.Property<int>("ProtectionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UpdatedSystemUserId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("ProtectionTypeId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("BlazorAV.Core.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParentComapnyId")
                        .HasColumnType("int");

                    b.Property<bool>("PortalAccess")
                        .HasColumnType("bit");

                    b.Property<int>("UpdatedSystemUserId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("BlazorAV.Core.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("DesignationDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("LastDateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedSystemUserId")
                        .HasColumnType("int");

                    b.HasKey("DesignationId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Designation", (string)null);
                });

            modelBuilder.Entity("BlazorAV.Core.Models.ProtectionType", b =>
                {
                    b.Property<int>("ProtectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProtectionId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProtectionDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UpdatedSystemUserId")
                        .HasColumnType("int");

                    b.HasKey("ProtectionId");

                    b.HasIndex("CompanyId");

                    b.ToTable("ProtectionType", (string)null);
                });

            modelBuilder.Entity("BlazorAV.Core.Models.Client", b =>
                {
                    b.HasOne("BlazorAV.Core.Models.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAV.Core.Models.Designation", "Designation")
                        .WithMany("Clients")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAV.Core.Models.ProtectionType", "Protection")
                        .WithMany("Clients")
                        .HasForeignKey("ProtectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Designation");

                    b.Navigation("Protection");
                });

            modelBuilder.Entity("BlazorAV.Core.Models.Designation", b =>
                {
                    b.HasOne("BlazorAV.Core.Models.Company", "Company")
                        .WithMany("Designations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BlazorAV.Core.Models.ProtectionType", b =>
                {
                    b.HasOne("BlazorAV.Core.Models.Company", "Company")
                        .WithMany("ProtectionTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BlazorAV.Core.Models.Company", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Designations");

                    b.Navigation("ProtectionTypes");
                });

            modelBuilder.Entity("BlazorAV.Core.Models.Designation", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("BlazorAV.Core.Models.ProtectionType", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
